import type { Metadata } from "next";
import Navbar from "@/components/Navbar";

import "./globals.css";



export const metadata: Metadata = {
  title: "ShopNest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
     
        
        <Navbar />
        {children}

         
    </>
  );
}
