import type { Metadata } from "next";
// import { } from "next/font/google";
import { Poppins, Playfair_Display} from "next/font/google";
import "./globals.css";
import Providers from "@/components/SessionProvider";



const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-playfair",
});


export const metadata: Metadata = {
  title: "QuickCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable}  ${playfair.variable} font-poppins`}
    >
      <body className="min-h-full flex flex-col">
       
        <Providers>
           {children}

        </Providers>

       

      
        </body>
    </html>
  );
}
