import type { Metadata } from "next";

import "./globals.css";



export const metadata: Metadata = {
  title: "ShopNest",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    
        {children} 
     
    </>
  );
}
